.TH IVS 1 "October 2010" "ivs 2.9" "User Manuals"
.SH NAME
ivs \- interactive volume segmentation

.SH SYNOPSIS
ivs [ \fIfilename\fR ]

.SH DESCRIPTION
IVS is the interactive volume segmentation tool developed at the
Institute of Computing, Unicamp. It displays and segments
3D images. It provides classical pre-processing filters and
cuting-edge segmentation operators based on the Differential IFT.
A usage guide is available from the website listed on the
bottom of this page. If a command-line argument is given,
IVS will try to load it as a volume file.

.SH AUTHORS
IVS was written by Felipe Bergo <bergo@liv.ic.unicamp.br> and
Alexandre Falcao <afalcao@ic.unicamp.br>. Information
about IVS and associated utilities can be found at

.I http://www.liv.ic.unicamp.br/~bergo/ivs

.SH "SEE ALSO"
.BR ana2scn (1),
.BR dicom2scn (1),
.BR scn2ana (1),
.BR scntool (1),
.BR scn (5)
