#!/usr/bin/perl

$ftconfig = "";
$ftpath = `which freetype-config 2>/dev/null`;
if ($? == 0 && $ftpath) {
    $ftconfig = "freetype-config";
} else {
    $ftconfig = "pkg-config freetype2";
}

my $flags = `$ftconfig --cflags`;
my $libs  = `$ftconfig --libs`;
chomp $flags;
chomp $libs;

my $system = `uname -s`;
if ($system =~ /^Darwin/) {
    $libs .= " -L/opt/homebrew/lib";
}

$flags .= " -g";
$libs .= ' -lm -lpthread -lbz2 -lpng -lz';


if (@ARGV == 0) {
    print "usage: bi-config [--cflags] [--libs]\n\n";
    print "@ARGV \n";
    exit 1;
}

foreach $i (@ARGV) {

    print $flags . ' ' if ($i eq '--cflags');
    print $libs  . ' ' if ($i eq '--libs');
	
}

exit 0;
