#!/usr/bin/perl

my $flags = `pkg-config --cflags freetype2`;
my $libs  = `pkg-config --libs freetype2`;
chomp $flags;
chomp $libs;

my $system = `uname -s`;
if ($system =~ /^Darwin/) {
    $libs .= " -L/opt/homebrew/lib";
}

$flags .= " -g";
$libs .= ' -lm -lpthread -lbz2 -lpng -lz';


if (@ARGV == 0) {
    print "usage: bi-config [--cflags] [--libs]\n\n";
    print "@ARGV \n";
    exit 1;
}

foreach $i (@ARGV) {

    print $flags . ' ' if ($i eq '--cflags');
    print $libs  . ' ' if ($i eq '--libs');
	
}

exit 0;
